//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCloth.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClothStorage
    {
        public int Id { get; set; }
        public double Article { get; set; }
        public string Width { get; set; }
    
        public virtual Cloth Cloth { get; set; }
    }
}
