//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCloth.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FurnitureStorage
    {
        public int Id { get; set; }
        public int IdFurniture { get; set; }
        public string Count { get; set; }
    
        public virtual Furniture Furniture { get; set; }
    }
}
