//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectCloth.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int Number { get; set; }
        public System.DateTime Date { get; set; }
        public int IdOrderItem { get; set; }
        public int IdStage { get; set; }
        public int IdCustomer { get; set; }
        public Nullable<int> IdManager { get; set; }
        public Nullable<int> Cost { get; set; }
    
        public virtual OrderItem OrderItem { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
